<a href="https://colab.research.google.com/github/lifod/TSC/blob/main/4%EC%9B%94_24%EC%9D%BC_%EC%97%B0%EB%A6%BD%EB%B0%A9%EC%A0%95%EC%8B%9D%EA%B3%BC_%ED%96%89%EB%A0%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello world")

print("방학은 언제 올까요?")

print(253)

print("내 나이는",20+15)

Hello world
방학은 언제 올까요?
253
내 나이는 35
253


str

In [ ]:
print(4//3)

print(5%3)

print(3**5)

1
2
243


In [ ]:
a=100

a+=20   # a=a+20

a-=10

a*=10

a/=5

print(a)

220.0


In [ ]:
print(5==20)

print(5!=20)

print(10<100)

print(5>=20)

print(type(10<100))

False
True
True
False
<class 'bool'>


In [ ]:
a=3.12

print(a)

b=2.41

print(a+b)

a='문자'

print(a)

c=float(input("원하는 숫자를 입력해주세요 : "))

print(b+c)

print(type(b)); print(type(c))

3.12
5.53
문자
원하는 숫자를 입력해주세요 : 5
7.41
<class 'float'>
<class 'float'>


In [ ]:
a='나이'
b=33
print('저의 %s는 %d살 입니다.'%(a,b))

c=3.14
print('단, 파이는 %.2f 입니다.'%c)       

저의 나이는 33살 입니다.
단, 파이는 3.14 입니다.


In [ ]:
a=3
if a>5:
  print("a는 5보다 큽니다")

b=int(input("정수를 입력해주세요 : "))

if b>0:
  print("b는 양수입니다")
if b<0:
  print("b는 음수입니다")
if b==0:
  print("b는 0입니다")

if b>0:
  print("b는 양수입니다")
elif b<0:
  print("b는 음수입니다")
if b==0:
  print("b는 0입니다")


정수를 입력해주세요 : -21
b는 음수입니다


In [ ]:
a=int(input("1이상의 정수를 입력해주세요 : "))

if a%2==0:
  print("a는 짝수입니다")

else :
  print("a는 홀수입니다")

1이상의 정수를 입력해주세요 : 9
a는 홀수입니다


In [ ]:
b=int(input("정수를 입력해주세요 : "))

if b>0:
  print("b는 양수입니다")
elif b<0:
  print("b는 음수입니다")
else:
  print("b는 0입니다")


정수를 입력해주세요 : 4
b는 양수입니다


In [ ]:
def xbox(x) :
  if x>0:
    return("x는 양수입니다")
  elif x<0:
    return("x는 음수입니다")
  else:
    return("x는 0입니다")

xbox(6)

def equation(x):
  y=x**2-3*x+2
  return y

equation(10)


def my_int(n):
  if n>0:
    return("%d은 양수입니다"%n)
  elif n<0:
    return("%d은 음수입니다"%n)
  else:
    return("%d은 0입니다"%n)

my_int(-24)


'-24은 음수입니다'

In [ ]:
my_variable=5

def my_equation(x):
  global my_variable
  my_variable=my_variable+5
  return my_variable

my_equation(4)

10

In [ ]:
a=range(5)
b=range(4)
c=range(2,5)

d=list(a)
print(d)

e=list(c)
print(e)

[0, 1, 2, 3, 4]
[2, 3, 4]


In [ ]:
a=[[1,2,3,4],
   [5,6,7,8]]

print(a[1][1:3])

[6, 7]


In [ ]:
import numpy as np

a=np.array([[1,2,3,4],[5,6,7,8]])
b=[[1,2,3,4],[5,6,7,8]]

a+b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

###[1] 행렬의 원소가 될 a, b, c, d, e, f를 설정 [float, input 사용]


In [ ]:
a=float(input("a를 입력해주세요"))
b=float(input("b를 입력해주세요"))
c=float(input("c를 입력해주세요"))
d=float(input("d를 입력해주세요"))
e=float(input("e를 입력해주세요"))
f=float(input("f를 입력해주세요"))

KeyboardInterrupt: ignored

###[2]numpy 모듈을 import한 후 numpy 배열로 행렬을 설정해주세요


In [ ]:
import numpy as np 

my_equ=np.array([[a,b,e],
                  [c,d,f]])   

my_copy=np.array([[0,0,0],
                  [0,0,0]]) 


[[1 1 1]
 [1 1 1]]


###[3]기본 행 연산을 수행할 수 있는 함수 3개를 만들어 주세요 

In [ ]:
def ero1(x,y):     
  global my_equ  
  my_equ[x]=my_equ[x]*1/my_equ[x][y]  


def ero2(x,y,z): 
  global my_equ 
  my_equ[y]=my_equ[y]-my_equ[x]*my_equ[y][z]  


def ero3():       
  global my_equ  
  global my_copy 
  my_copy[0]=my_equ[1]
  my_copy[1]=my_equ[0]
  my_equ=my_copy          

###[4]ad-bc, af-ce의 값에 따라 결정되는 해의 존재성을 구현하고 해가 존재할 경우 해를 표현해주세요

In [ ]:
if a*d-b*c==0:

  if a*f-c*e==0:
    print("무수히 많은 해가 존재합니다.")

  else:
    print("해가 존재하지 않습니다")
  
else:
  if a==0: 
    ero3()
    ero1(0,0) 
    ero2(0,1,0)
    ero1(1,1)
    ero2(1,0,1)
    print("해는 (x,y)=(%f,%f)입니다"%(my_equ[0][2],my_equ[1][2]))
  else:
    ero1(0,0)
    ero2(0,1,0)
    ero1(1,1)
    ero2(1,0,1)
    print("해는 (x,y)=(%f,%f)입니다"%(my_equ[0][2],my_equ[1][2]))

###최종 코드

In [ ]:
a=float(input("a를 입력해주세요"))
b=float(input("b를 입력해주세요"))
c=float(input("c를 입력해주세요"))
d=float(input("d를 입력해주세요"))
e=float(input("e를 입력해주세요"))
f=float(input("f를 입력해주세요"))

import numpy as np         #넘파이 라이브러리를 np로 import합니다(약칭)
my_equ=np.array([[a,b,e],
                  [c,d,f]])     #계수행렬에 상수항을 첨가한 행렬을 정의합니다.
my_copy=np.array([[0,0,0],
                  [0,0,0]])     # 영행렬 정의 - 행교환에서 사용하기 위해 

def ero1(x,y):     #기본행연산 (곱)
  global my_equ   #함수 외부에 있는 변수 설정
  my_equ[x]=my_equ[x]*1/my_equ[x][y]  # x행을 (x,y)성분으로 나눈다.

def ero2(x,y,z):  #기본행연산(한 행의 배수를 다른행에 더함)
  global my_equ  #함수 외부에 있는 변수 설정
  my_equ[y]=my_equ[y]-my_equ[x]*my_equ[y][z]  # x행에 (y,z)성분을 곱한 후 y행에서 뺀다.


def ero3():       #기본행연산(두 행을 교환)
  global my_equ  #함수 외부에 있는 변수 설정
  global my_copy  #함수 외부에 있는 변수 설정
  my_copy[0]=my_equ[1]
  my_copy[1]=my_equ[0]
  my_equ=my_copy            #영행렬에 바뀐 행을 저장 후 행렬로 다시 지정함.

if a*d-b*c==0:

  if a*f-c*e==0:
    print("무수히 많은 해가 존재합니다.")

  else:
    print("해가 존재하지 않습니다")
  
else:
  if a==0: 
    ero3()
    ero1(0,0) #동일하게 반복되는 부분에 대한 함수를 새롭게 정의하여 최소화 가능
    ero2(0,1,0)
    ero1(1,1)
    ero2(1,0,1)
    print("해는 (x,y)=(%f,%f)입니다"%(my_equ[0][2],my_equ[1][2]))
  else:
    ero1(0,0)
    ero2(0,1,0)
    ero1(1,1)
    ero2(1,0,1)
    print("해는 (x,y)=(%f,%f)입니다"%(my_equ[0][2],my_equ[1][2]))
   

a를 입력해주세요3
b를 입력해주세요6
c를 입력해주세요1
d를 입력해주세요7
e를 입력해주세요2
f를 입력해주세요5
해는 (x,y)=(-1.066667,0.866667)입니다
