<a href="https://colab.research.google.com/github/lifod/TSC/blob/main/%EC%BD%94%EC%82%AC%EC%9D%B8%EC%9C%A0%EC%82%AC%EB%8F%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ▶빈도수 벡터를 이용한 코사인 유사도(빈도수 직접 입력)


In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

sen1=np.array([5,4,4,0,0])
sen2=np.array([1,0,0,5,0])
sen3=np.array([0,0,0,4,5])
sen4=np.array([1,4,0,4,0])
column=["사과","바나나","수박","멜론","참외"]
bow=[sen1,sen2,sen3,sen4]
df=pd.DataFrame(bow,columns=column,index=['sen'+str(i+1) for i in range(4)])
df

사과  바나나  수박  멜론  참외
sen1   5    4   4   0   0
sen2   1    0   0   5   0
sen3   0    0   0   4   5
sen4   1    4   0   4   0

In [ ]:
cosine_sim = cosine_similarity(df, df)
cosine_sim

array([[1.        , 0.12988108, 0.        , 0.48420012],
       [0.12988108, 1.        , 0.61256389, 0.71692818],
       [0.        , 0.61256389, 1.        , 0.4349818 ],
       [0.48420012, 0.71692818, 0.4349818 , 1.        ]])

In [ ]:
df=pd.DataFrame(cosine_sim,columns=['sen'+str(i+1) for i in range(4)],index=['sen'+str(i+1) for i in range(4)])
df

sen1      sen2      sen3      sen4
sen1  1.000000  0.129881  0.000000  0.484200
sen2  0.129881  1.000000  0.612564  0.716928
sen3  0.000000  0.612564  1.000000  0.434982
sen4  0.484200  0.716928  0.434982  1.000000

# ▶문서단어행렬(DTM)

In [ ]:
import os

file=open("similarity.txt",encoding='utf8')
lines=file.readlines()

print(lines[:2])

['Think like a man od action and act like man of thought. \n', 'Try not to become a man of success but rather try to become a man of value. \n']


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vector = CountVectorizer(stop_words='english')
bow = vector.fit_transform(lines)

print(bow.toarray())
print(vector.vocabulary_)

[[1 1 0 0 2 2 1 0 1 1 0 0]
 [0 0 0 0 0 2 0 1 0 0 2 1]
 [0 0 1 1 0 0 0 0 0 0 0 0]]
{'think': 8, 'like': 4, 'man': 5, 'od': 6, 'action': 1, 'act': 0, 'thought': 9, 'try': 10, 'success': 7, 'value': 11, 'liberty': 3, 'death': 2}


# ▶DataFrame

In [ ]:
import pandas as pd

columns=[]
for k, v in sorted(vector.vocabulary_.items(), key=lambda item:item[1]):
  columns.append(k)

df=pd.DataFrame(bow.toarray(), columns=columns)
df

act  action  death  liberty  like  man  od  success  think  thought  try  \
0    1       1      0        0     2    2   1        0      1        1    0   
1    0       0      0        0     0    2   0        1      0        0    2   
2    0       0      1        1     0    0   0        0      0        0    0   

   value  
0      0  
1      1  
2      0

# ▶코사인 유사도(cosine_similarity)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(df, df)
cosine_sim

array([[1.        , 0.35082321, 0.        ],
       [0.35082321, 1.        , 0.        ],
       [0.        , 0.        , 1.        ]])

# ▶한글의 토큰화 문제

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

corpus=["사과를 좋아하고 바나나도 좋아한다",
        "사과를 좋아하고 바나나는 사과보다 더 좋아한다",
        "사과는 좋아하지만 바나나는 싫어한다"]

vector = CountVectorizer(stop_words='english')
bow = vector.fit_transform(corpus)

print(bow.toarray())
print(vector.vocabulary_)

[[0 1 0 1 0 0 1 0 1]
 [1 0 0 1 1 0 1 0 1]
 [1 0 1 0 0 1 0 1 0]]
{'사과를': 3, '좋아하고': 6, '바나나도': 1, '좋아한다': 8, '바나나는': 0, '사과보다': 4, '사과는': 2, '좋아하지만': 7, '싫어한다': 5}


# ▶한국어 자연어 처리 konlpy

In [2]:
!set -x\
&& pip install konlpy\
&& curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh | bash -x

+ pip install konlpy
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 76.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 496.6/496.6 kB 32.2 MB/s eta 0:00:00
+ bash -x
+ curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh
+ mecab_dicdir=/usr/local/lib/mecab/dic/mecab-ko-dic
+ set -e
++ uname
+ os=Linux
+ [[ ! Linux == \L\i\n\u\x ]]
+ hash sudo
+ sudo=sudo
+ python=python3
+ hash pyenv
+ at_user_site=
++ check_python_site_location_is_writable
++ python3 -
+ [[ 1 == \0 ]]
+ hash automake
+ hash mecab
+ echo 'Install mecab-ko'
Install mecab-ko
+ install_mecab_ko
+ cd /tmp
+ curl -LO https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1381k  100 1381k    0     0  1505k      0 --

# ▶파일 읽어오기[명사만]


In [ ]:
import pandas as pd
similarity = pd.read_csv("example.csv",encoding='cp949')
similarity.head()

opinion
0             슈퍼까지 가는게 힘들어
1                   육아가 쉽다
2            데이트 명소를 갖고 싶다
3  상가를 좀 더 활기차게 만들었으면 좋겠다.
4           밤길이 어둡다 (BB지구)

In [ ]:
similarity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   opinion  83 non-null     object
dtypes: object(1)
memory usage: 792.0+ bytes


# ▶형태소 분석

In [ ]:
from konlpy.tag import Twitter

twt=Twitter()
text = "상가를 좀 더 활기차게 만들었으면 좋겠다."
words = twt.pos(text)
words

/usr/local/lib/python3.8/dist-packages/konlpy/tag/_okt.py:17: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')


[('상가', 'Noun'),
 ('를', 'Josa'),
 ('좀', 'Noun'),
 ('더', 'Noun'),
 ('활기차게', 'Adjective'),
 ('만들었으면', 'Verb'),
 ('좋겠다', 'Adjective'),
 ('.', 'Punctuation')]

In [ ]:
from collections import Counter

# stop_words = ["모두","더","좀"]
parts = ["Noun"]
all_words_df = pd.DataFrame()

for n in range(len(similarity)):
    text = similarity["opinion"].iloc[n]
    words = twt.pos(text)
    words_df = pd.DataFrame()
    words_arr = []

    for i in words:
      word_tmp = i[0]
      part = i[1]
      if not (part in parts):continue
      # if word_tmp in stop_words:continue
      if len(word_tmp)==1:continue
      words_arr.append(word_tmp)
      words_arr_counter=Counter(words_arr)


    for i in words:
        word_tmp = i[0]
        part = i[1]
        if not (part in parts):continue
        # if word_tmp in stop_words:continue
        if len(word_tmp)==1:continue

        words_df[word_tmp] = [words_arr_counter[word_tmp]]
    all_words_df = pd.concat([all_words_df, words_df] ,ignore_index=True)

all_words_df.head()

슈퍼   육아  데이트   명소   상가   밤길   지구  쓰레기  처리  영화관  ...  대기  아동  생활  상업시설  \
0  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN NaN  NaN  ... NaN NaN NaN   NaN   
1  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN NaN  NaN  ... NaN NaN NaN   NaN   
2  NaN  NaN  1.0  1.0  NaN  NaN  NaN  NaN NaN  NaN  ... NaN NaN NaN   NaN   
3  NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN NaN  NaN  ... NaN NaN NaN   NaN   
4  NaN  NaN  NaN  NaN  NaN  1.0  1.0  NaN NaN  NaN  ... NaN NaN NaN   NaN   

   사이클링  코스  축제  성대  근처  살기  
0   NaN NaN NaN NaN NaN NaN  
1   NaN NaN NaN NaN NaN NaN  
2   NaN NaN NaN NaN NaN NaN  
3   NaN NaN NaN NaN NaN NaN  
4   NaN NaN NaN NaN NaN NaN  

[5 rows x 164 columns]

In [ ]:
all_words_df = all_words_df.fillna(0)
all_words_df.head()

슈퍼   육아  데이트   명소   상가   밤길   지구  쓰레기   처리  영화관  ...   대기   아동   생활  상업시설  \
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   0.0   
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   0.0   
2  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   0.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   0.0   
4  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   0.0   

   사이클링   코스   축제   성대   근처   살기  
0   0.0  0.0  0.0  0.0  0.0  0.0  
1   0.0  0.0  0.0  0.0  0.0  0.0  
2   0.0  0.0  0.0  0.0  0.0  0.0  
3   0.0  0.0  0.0  0.0  0.0  0.0  
4   0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 164 columns]

In [ ]:
import numpy as np
from numpy.linalg import norm

target_text = all_words_df.iloc[1]

cos_sim = []
for i in range(len(all_words_df)):
    cos_text = all_words_df.iloc[i]
    cos = np.dot(target_text, cos_text) / (norm(target_text) * norm(cos_text))
    cos_sim.append(cos)
all_words_df["cos_sim"] = cos_sim
all_words_df.sort_values("cos_sim",ascending=False).head()

슈퍼   육아  데이트   명소   상가   밤길   지구  쓰레기   처리  영화관  ...   아동   생활  상업시설  \
1   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0   
71  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0   
10  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0   
53  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0   
60  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0   

    사이클링   코스   축제   성대   근처   살기   cos_sim  
1    0.0  0.0  0.0  0.0  0.0  0.0  1.000000  
71   0.0  0.0  0.0  0.0  0.0  0.0  0.707107  
10   0.0  0.0  0.0  0.0  0.0  0.0  0.707107  
53   0.0  0.0  0.0  0.0  0.0  0.0  0.000000  
60   0.0  0.0  0.0  0.0  0.0  0.0  0.000000  

[5 rows x 165 columns]

# ▶파일 읽어오기[명사, 형용사]


In [3]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from konlpy.tag import Okt  # 형태소 분석기를 위한 라이브러리 (Okt 사용)

# 1. 한국어 텍스트를 받기
corpus = [
    "사과를 좋아하고 바나나도 좋아한다",
    "사과를 좋아하고 바나나는 사과보다 더 좋아한다",
    "사과는 좋아하지만 바나나는 싫어한다",
    "사과와 바나나를 모두 싫어한다",
    "사과를 싫어하고 바나나도 싫어한다"]

# 2. 형태소 분석을 통해 명사만 추출하는 함수
okt = Okt()

def preprocess(text):
    # 명사와 형용사를 추출
    pos = okt.pos(text)  # 품사 태깅
    # 명사와 형용사만 추출
    return ' '.join([word for word, tag in pos if tag in ['Noun', 'Adjective']])

# 텍스트 전처리 (명사만 추출)
processed_corpus = [preprocess(text) for text in corpus]

# 3. TF-IDF 벡터화
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(processed_corpus)

# 4. TF-IDF 행렬을 DataFrame으로 변환
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())

# 5. 코사인 유사도 계산
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# 6. 결과 출력
print("TF-IDF 행렬 (명사):")
print(tfidf_df)

print("\n코사인 유사도 행렬:")
print(cosine_sim)

# 상위 5개의 유사도 결과를 출력 (자기 자신과의 유사도도 포함)
cosine_sim_df = pd.DataFrame(cosine_sim, columns=[f"Text {i+1}" for i in range(len(corpus))],
                             index=[f"Text {i+1}" for i in range(len(corpus))])

# 유사도 높은 순으로 정렬
print("\n유사도 순으로 정렬된 결과:")
print(cosine_sim_df)


TF-IDF 행렬 (명사):
         모두       바나나        사과
0  0.000000  0.707107  0.707107
1  0.000000  0.447214  0.894427
2  0.000000  0.707107  0.707107
3  0.829279  0.395156  0.395156
4  0.000000  0.707107  0.707107

코사인 유사도 행렬:
[[1.         0.9486833  1.         0.55883481 1.        ]
 [0.9486833  1.         0.9486833  0.53015725 0.9486833 ]
 [1.         0.9486833  1.         0.55883481 1.        ]
 [0.55883481 0.53015725 0.55883481 1.         0.55883481]
 [1.         0.9486833  1.         0.55883481 1.        ]]

유사도 순으로 정렬된 결과:
          Text 1    Text 2    Text 3    Text 4    Text 5
Text 1  1.000000  0.948683  1.000000  0.558835  1.000000
Text 2  0.948683  1.000000  0.948683  0.530157  0.948683
Text 3  1.000000  0.948683  1.000000  0.558835  1.000000
Text 4  0.558835  0.530157  0.558835  1.000000  0.558835
Text 5  1.000000  0.948683  1.000000  0.558835  1.000000
